version: "3.3"

services:
  db:
    image: mysql:8
    container_name: login-mysql
    restart: always
    environment:
      MYSQL_DATABASE: freeradius
      MYSQL_USER: login
      MYSQL_PASSWORD: login
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  login:
    container_name: login
    build: .
    environment:
      - MYSQL_DB_SERVER=login-mysql
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_NAME=freeradius
      - MYSQL_DB_USER=login
      - MYSQL_DB_PW=login
      - GECO_API_URL=https://geco.ethz.ch/api/v2/auth
      - GECO_API_KEY=blub
      - OIDC_ISSUER=https://geco.ethz.ch
      - OIDC_REDIRECT_URL=https://login-ng.lan.geco.ethz.ch/callback
      - OIDC_CLIENT_ID=login-ng
      - OIDC_CLIENT_SECRET=abcdef
      - GECO_LAN_ID=1
      - GECO_USERSTATUS_ENDPOINT=https://geco.ethz.ch/api/v1/lan_parties/%s/me
      - SESSION_SECRET=abcdef
      - GIN_MODE=release
    depends_on:
      - db
    ports:
      - 8080:8080
